version: '3.8'

services:
  telegram-sticker-bot:
    build: .
    container_name: telegram-sticker-bot
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - STICKER_PACKS=${STICKER_PACKS}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - ALLOWED_CHATS=${ALLOWED_CHATS:-}
      - MODE=${MODE:-polling}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app